import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
// imports
import { HeaderComponents } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="es">
			<body className={inter.className} data-bs-theme="dark">
				<HeaderComponents />
				{children}
			</body>
		</html>
	);
}
